// Mock data for development when database is not available
export const mockProducts = [
  {
    id: "mock-1",
    type: "PATTERN",
    title: "Classic Oxford Shoe Pattern",
    slug: "classic-oxford-shoe-pattern",
    description: "A timeless oxford shoe pattern perfect for beginners. Includes detailed instructions and sizing guide.",
    priceCents: 2999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800",
    metadata: { style: "Oxford", tools: ["Leather", "Thread", "Needles", "Last"] },
    variants: [
      { id: "v1", title: "Beginner", skillLevel: "BEGINNER" },
      { id: "v2", title: "Intermediate", skillLevel: "INTERMEDIATE" },
    ],
  },
  {
    id: "mock-2",
    type: "PATTERN",
    title: "Derby Shoe Pattern",
    slug: "derby-shoe-pattern",
    description: "Versatile derby shoe pattern with multiple closure options.",
    priceCents: 3499,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800",
    metadata: { style: "Derby", tools: ["Leather", "Thread", "Needles", "Last"] },
    variants: [
      { id: "v3", title: "Intermediate", skillLevel: "INTERMEDIATE" },
      { id: "v4", title: "Advanced", skillLevel: "ADVANCED" },
    ],
  },
  {
    id: "mock-3",
    type: "PATTERN",
    title: "Loafers Pattern Collection",
    slug: "loafers-pattern-collection",
    description: "Complete collection of loafer patterns including penny loafers and tassel loafers.",
    priceCents: 3999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800",
    metadata: { style: "Loafers", tools: ["Leather", "Thread", "Needles", "Last"] },
    variants: [
      { id: "v5", title: "Beginner", skillLevel: "BEGINNER" },
      { id: "v6", title: "Advanced", skillLevel: "ADVANCED" },
    ],
  },
  {
    id: "mock-4",
    type: "MATERIAL",
    title: "Premium Italian Calf Leather",
    slug: "premium-italian-calf-leather",
    description: "High-quality Italian calf leather in various colors. Perfect for dress shoes.",
    priceCents: 8999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800",
    metadata: { thickness: "2-3mm", temper: "Medium", color: "Black, Brown, Tan" },
    variants: [],
  },
  {
    id: "mock-5",
    type: "MATERIAL",
    title: "English Bridle Leather",
    slug: "english-bridle-leather",
    description: "Traditional English bridle leather, known for its durability and patina.",
    priceCents: 10999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800",
    metadata: { thickness: "3-4mm", temper: "Firm", color: "Brown, Black" },
    variants: [],
  },
  {
    id: "mock-6",
    type: "MATERIAL",
    title: "Suede Leather Pack",
    slug: "suede-leather-pack",
    description: "Soft suede leather in multiple colors for casual shoes.",
    priceCents: 6999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800",
    metadata: { thickness: "1.5-2mm", temper: "Soft", color: "Various" },
    variants: [],
  },
  {
    id: "mock-7",
    type: "GUIDE",
    title: "Complete Beginner's Guide to Shoemaking",
    slug: "complete-beginners-guide-shoemaking",
    description: "Learn the fundamentals of shoemaking from tools to finishing techniques.",
    priceCents: 4999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800",
    metadata: { topic: "Fundamentals", duration: "8 hours", prerequisites: "None" },
    variants: [],
  },
  {
    id: "mock-8",
    type: "GUIDE",
    title: "Advanced Stitching Techniques",
    slug: "advanced-stitching-techniques",
    description: "Master advanced hand-stitching and machine techniques for professional results.",
    priceCents: 5999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800",
    metadata: { topic: "Techniques", duration: "6 hours", prerequisites: "Basic shoemaking knowledge" },
    variants: [],
  },
  {
    id: "mock-9",
    type: "GUIDE",
    title: "Last Making and Fitting",
    slug: "last-making-fitting",
    description: "Comprehensive guide to creating and fitting shoe lasts.",
    priceCents: 6999,
    currency: "usd",
    status: "PUBLISHED",
    coverImageUrl: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800",
    metadata: { topic: "Last Making", duration: "10 hours", prerequisites: "Intermediate level" },
    variants: [],
  },
]

